# Generated by Django 4.2.22 on 2025-12-04 18:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
