# Generated by Django 4.2.22 on 2025-12-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
    ]
