# Generated by Django 4.2.22 on 2025-12-08 16:43

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name=models.ImageField(blank=True, null=True, upload_to='')),
            preserve_default=False,
        ),
    ]
